'use client'

import * as React from 'react'
import { cn } from '@/lib/utils'
import {
  X, AlertTriangle, Clock, CheckCircle2, ChevronRight, FileText,
  Bot, Shield, History, ExternalLink, ChevronDown,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  type AuditOccurrence, type ChecklistResult, type OverallResult,
  occurrenceStatusBadge, overallResultBadge, findingSeverityBadge,
  checklistResultBadge,
} from '@/lib/governance-data'

interface OccurrenceDetailProps {
  occurrence: AuditOccurrence
  onClose: () => void
  currentUserRole?: string
}

const RESULT_OPTIONS: ChecklistResult[] = ['Pass', 'Fail', 'Partial', 'N/A']
const OVERALL_OPTIONS: OverallResult[] = ['Pass', 'Fail', 'Partial']

export function OccurrenceDetail({ occurrence, onClose, currentUserRole = 'Portfolio Controls Lead' }: OccurrenceDetailProps) {
  const [activeTab, setActiveTab] = React.useState<'checklist' | 'findings' | 'trail'>('checklist')
  const [checklistState, setChecklistState] = React.useState<Record<string, ChecklistResult>>(
    Object.fromEntries(occurrence.checklist.map((c) => [c.itemId, c.result]))
  )
  const [checklistNotes, setChecklistNotes] = React.useState<Record<string, string>>(
    Object.fromEntries(occurrence.checklist.map((c) => [c.itemId, c.note]))
  )
  const [overallResult, setOverallResult] = React.useState<OverallResult | null>(occurrence.overallResult)
  const [status, setStatus] = React.useState(occurrence.status)
  const [submitted, setSubmitted] = React.useState(false)
  const [approved, setApproved] = React.useState(false)
  const [showTrailFull, setShowTrailFull] = React.useState(false)

  const sb = occurrenceStatusBadge(status)
  const canEdit = ['In Progress', 'Scheduled'].includes(status) &&
    ['Auditor', 'Portfolio Controls Lead', 'Senior Director', 'Portfolio Director', 'Contractor Compliance Reviewer', 'Risk Owner'].includes(currentUserRole)
  const canApprove = status === 'Pending Review' &&
    ['Portfolio Controls Lead', 'Senior Director', 'Portfolio Director'].includes(currentUserRole)

  const handleSubmit = () => {
    setStatus('Pending Review')
    setSubmitted(true)
  }

  const handleApprove = () => {
    setStatus('Completed')
    setApproved(true)
  }

  const allCompleted = occurrence.checklist.length === 0 ||
    occurrence.checklist.every((c) => checklistState[c.itemId] && checklistState[c.itemId] !== 'Pass' || checklistState[c.itemId] === 'Pass' || checklistState[c.itemId] === 'N/A' || checklistState[c.itemId] === 'Fail' || checklistState[c.itemId] === 'Partial')

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center sm:p-4 bg-black/40 backdrop-blur-sm">
      <div className="bg-card border border-line rounded-t-2xl sm:rounded-2xl shadow-xl w-full sm:max-w-3xl max-h-[92vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-start justify-between px-5 py-4 border-b border-line">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap mb-1">
              <span className="text-[10px] font-mono text-muted-foreground">{occurrence.id}</span>
              {occurrence.isAutoGenerated && (
                <span className="px-1.5 py-0.5 rounded bg-teal/10 text-teal border border-teal/20 text-[9px] font-semibold flex items-center gap-1">
                  <Bot className="w-2.5 h-2.5" />A-206
                </span>
              )}
              {occurrence.isAtRisk && (
                <span className="px-1.5 py-0.5 rounded bg-amber-bg text-amber border border-amber/30 text-[9px] font-semibold flex items-center gap-1">
                  <AlertTriangle className="w-2.5 h-2.5" />At Risk
                </span>
              )}
              <span className={cn('px-2 py-0.5 rounded-md border text-[10px] font-semibold flex items-center gap-1', sb.cls)}>
                <span className={cn('w-1.5 h-1.5 rounded-full', sb.dot)} />{sb.label}
              </span>
            </div>
            <h2 className="text-[14px] font-semibold text-foreground leading-snug">{occurrence.scheduleName}</h2>
            <p className="text-[11.5px] text-muted-foreground mt-0.5">
              {occurrence.projectNames.join(', ')} · Due {occurrence.dueDate} · Auditor: {occurrence.auditorName}
            </p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-secondary text-muted-foreground hover:text-foreground ml-3 shrink-0">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-1 px-5 pt-3 pb-0 border-b border-line">
          {(['checklist', 'findings', 'trail'] as const).map((t) => (
            <button
              key={t}
              onClick={() => setActiveTab(t)}
              className={cn(
                'px-3 py-2 text-[12px] font-semibold capitalize border-b-2 transition-all -mb-px',
                activeTab === t ? 'border-gold text-foreground' : 'border-transparent text-muted-foreground hover:text-foreground'
              )}
            >
              {t === 'findings' ? `Findings (${occurrence.findings.length})` : t === 'trail' ? `Trail (${occurrence.trailEntries.length})` : 'Checklist'}
            </button>
          ))}
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-5 py-4 h-96">
          {activeTab === 'checklist' && (
            <div className="space-y-3">
              {occurrence.checklist.length === 0 ? (
                <div className="py-10 text-center">
                  <Clock className="w-8 h-8 text-muted-foreground/30 mx-auto mb-2" />
                  <p className="text-[13px] text-muted-foreground">Checklist items will appear when this occurrence is in progress.</p>
                </div>
              ) : (
                <>
                  {occurrence.checklist.map((item) => {
                    const result = checklistState[item.itemId]
                    const rb = checklistResultBadge(result)
                    return (
                      <div key={item.itemId} className={cn(
                        'rounded-xl border p-4 transition-colors',
                        result === 'Fail' ? 'border-red/30 bg-red-bg/30' :
                        result === 'Partial' ? 'border-amber/30 bg-amber-bg/30' :
                        result === 'Pass' ? 'border-green/20 bg-green-bg/30' :
                        'border-line bg-secondary/20'
                      )}>
                        <div className="flex flex-col sm:flex-row sm:items-start gap-3">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 mb-1">
                              <span className="text-[10px] font-mono text-muted-foreground">{item.itemId}</span>
                              {item.likelihood !== undefined && (
                                <span className="text-[10px] text-muted-foreground">
                                  L{item.likelihood}×I{item.impact}={item.score} · {item.daysSinceReview}d ago
                                </span>
                              )}
                              {item.framework && (
                                <span className="text-[10px] text-muted-foreground">{item.framework}</span>
                              )}
                            </div>
                            <p className="text-[13px] font-semibold text-foreground">{item.itemName}</p>
                            {item.expiryDate && (
                              <p className={cn('text-[11px] mt-0.5', (item.daysToExpiry ?? 999) <= 30 ? 'text-red font-semibold' : (item.daysToExpiry ?? 999) <= 90 ? 'text-amber' : 'text-muted-foreground')}>
                                Expires {item.expiryDate} · {item.daysToExpiry} days
                              </p>
                            )}
                          </div>
                          {/* Result selector */}
                          <div className="flex items-center gap-1">
                            {RESULT_OPTIONS.map((opt) => {
                              const isSelected = result === opt
                              const cls = {
                                Pass: 'bg-green text-white border-green',
                                Fail: 'bg-red text-white border-red',
                                Partial: 'bg-amber text-white border-amber',
                                'N/A': 'bg-secondary text-muted-foreground border-line',
                              }[opt]
                              return (
                                <button
                                  key={opt}
                                  disabled={!canEdit}
                                  onClick={() => setChecklistState((prev) => ({ ...prev, [item.itemId]: opt }))}
                                  className={cn(
                                    'px-2 py-1 rounded-md border text-[10.5px] font-semibold transition-all',
                                    isSelected ? cls : 'bg-secondary text-muted-foreground border-line hover:border-gold/30',
                                    !canEdit && 'opacity-60 cursor-default'
                                  )}
                                >
                                  {opt}
                                </button>
                              )
                            })}
                          </div>
                        </div>

                        {/* Note */}
                        <div className="mt-3">
                          <textarea
                            disabled={!canEdit}
                            value={checklistNotes[item.itemId] || ''}
                            onChange={(e) => setChecklistNotes((prev) => ({ ...prev, [item.itemId]: e.target.value }))}
                            rows={2}
                            placeholder="Add audit note…"
                            className="w-full px-3 py-2 text-[12px] rounded-lg border border-line bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-gold resize-none disabled:opacity-60"
                          />
                        </div>

                        {/* Evidence & fail reason */}
                        <div className="flex items-center gap-3 mt-2">
                          {item.evidence && item.evidence !== 'MISSING' && (
                            <span className="flex items-center gap-1 text-[11px] text-teal">
                              <FileText className="w-3 h-3" />{item.evidence}
                            </span>
                          )}
                          {item.failReason && (
                            <span className="px-2 py-0.5 rounded bg-red-bg text-red border border-red/20 text-[10px] font-semibold">
                              {item.failReason}
                            </span>
                          )}
                          {item.mitigationStatus && (
                            <span className={cn(
                              'px-2 py-0.5 rounded border text-[10px] font-semibold',
                              item.mitigationStatus === 'Done' ? 'bg-green-bg text-green border-green/30' :
                              item.mitigationStatus === 'Overdue' ? 'bg-red-bg text-red border-red/30' :
                              item.mitigationStatus === 'In-Progress' ? 'bg-teal/10 text-teal border-teal/20' :
                              'bg-secondary text-muted-foreground border-line'
                            )}>
                              Mitigation: {item.mitigationStatus}
                            </span>
                          )}
                        </div>
                      </div>
                    )
                  })}

                  {/* Overall result */}
                  {canEdit && (
                    <div className="rounded-xl border border-line bg-card p-4">
                      <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground mb-2">Overall Result</p>
                      <div className="flex items-center gap-2">
                        {OVERALL_OPTIONS.map((opt) => {
                          const cls = { Pass: 'bg-green text-white border-green', Fail: 'bg-red text-white border-red', Partial: 'bg-amber text-white border-amber' }[opt]
                          return (
                            <button
                              key={opt}
                              onClick={() => setOverallResult(opt)}
                              className={cn(
                                'px-4 py-2 rounded-lg border text-[12px] font-semibold transition-all',
                                overallResult === opt ? cls : 'bg-secondary text-muted-foreground border-line hover:border-gold/30'
                              )}
                            >{opt}</button>
                          )
                        })}
                      </div>
                    </div>
                  )}

                  {/* Submit / Approve */}
                  <div className="flex items-center gap-2 justify-end pt-2">
                    {canEdit && !submitted && (
                      <Button
                        size="sm"
                        disabled={!overallResult}
                        onClick={handleSubmit}
                        className="h-9 text-[12px] bg-gold text-navy border border-gold font-semibold"
                      >
                        Submit for Review
                      </Button>
                    )}
                    {canApprove && !approved && (
                      <Button
                        size="sm"
                        onClick={handleApprove}
                        className="h-9 text-[12px] bg-green text-white border-green font-semibold"
                      >
                        <CheckCircle2 className="w-3.5 h-3.5 mr-1.5" />Approve
                      </Button>
                    )}
                    {(submitted || status === 'Pending Review') && !approved && (
                      <span className="text-[12px] text-amber font-medium flex items-center gap-1.5">
                        <Clock className="w-3.5 h-3.5" />Awaiting review
                      </span>
                    )}
                    {(approved || status === 'Completed') && (
                      <span className="text-[12px] text-green font-semibold flex items-center gap-1.5">
                        <CheckCircle2 className="w-3.5 h-3.5" />Completed
                      </span>
                    )}
                  </div>
                </>
              )}
            </div>
          )}

          {activeTab === 'findings' && (
            <div className="space-y-3">
              {occurrence.findings.length === 0 ? (
                <div className="py-10 text-center">
                  <Shield className="w-8 h-8 text-muted-foreground/30 mx-auto mb-2" />
                  <p className="text-[13px] text-muted-foreground">No findings raised for this occurrence.</p>
                </div>
              ) : (
                occurrence.findings.map((f) => {
                  const fb = findingSeverityBadge(f.severity)
                  return (
                    <div key={f.id} className="rounded-xl border border-line bg-secondary/20 p-4">
                      <div className="flex items-start gap-3">
                        <span className={cn('w-2 h-2 rounded-full mt-1.5 shrink-0', fb.dot)} />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap mb-1">
                            <span className="text-[10px] font-mono text-muted-foreground">{f.id}</span>
                            <span className={cn('px-1.5 py-0.5 rounded border text-[9px] font-bold', fb.cls)}>{f.severity}</span>
                            <span className={cn(
                              'px-1.5 py-0.5 rounded border text-[9px] font-semibold',
                              f.status === 'Closed' ? 'bg-green-bg text-green border-green/30' :
                              f.status === 'In Progress' ? 'bg-teal/10 text-teal border-teal/20' :
                              'bg-amber-bg text-amber border-amber/30'
                            )}>{f.status}</span>
                          </div>
                          <p className="text-[13px] font-medium text-foreground leading-snug">{f.description}</p>
                          <div className="flex items-center gap-3 mt-2">
                            <span className="text-[11px] text-muted-foreground">Owner: <span className="font-semibold text-foreground">{f.remediationOwnerName}</span></span>
                            <span className="text-[11px] text-muted-foreground">Due: <span className={cn('font-semibold', f.dueDate < '2026-06-26' && f.status !== 'Closed' ? 'text-red' : 'text-foreground')}>{f.dueDate}</span></span>
                          </div>
                          <div className="mt-2 flex items-center gap-2">
                            <span className="text-[10.5px] text-teal flex items-center gap-1 cursor-pointer hover:underline">
                              <ExternalLink className="w-3 h-3" />View in Task Inbox
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  )
                })
              )}
            </div>
          )}

          {activeTab === 'trail' && (
            <div className="space-y-2">
              <p className="text-[11px] text-muted-foreground mb-3 flex items-center gap-1.5">
                <History className="w-3.5 h-3.5" />
                Append-only audit trail — entries cannot be edited or deleted.
              </p>
              {occurrence.trailEntries.map((entry, i) => (
                <div key={i} className="flex items-start gap-3 py-2.5 border-b border-line last:border-0">
                  <div className="w-6 h-6 rounded-full bg-secondary border border-line flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-[8px] font-bold text-muted-foreground">{entry.initials}</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-[12.5px] font-medium text-foreground">{entry.action}</p>
                    <p className="text-[10.5px] text-muted-foreground mt-0.5">{entry.user} · {entry.ts.replace('T', ' ').slice(0, 16)}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
